//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FoodExNepal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FoodItem
    {
        public FoodItem()
        {
            this.OrderDetails = new HashSet<OrderDetail>();
        }
    
        public int FoodItemId { get; set; }
        public string FoodItemName { get; set; }
        public int RestaurantId { get; set; }
        public int FoodCategoryId { get; set; }
        public string FoodDescription { get; set; }
        public Nullable<double> FoodItemRate { get; set; }
        public string FoodItemImage { get; set; }
        public string Rating { get; set; }
        public Nullable<bool> IsHotDeal { get; set; }
        public string HotDealDescription { get; set; }
        public string HotDealImage { get; set; }
    
        public virtual FoodCategory FoodCategory { get; set; }
        public virtual Restaurant Restaurant { get; set; }
        public virtual ICollection<OrderDetail> OrderDetails { get; set; }
    }
}
