//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FoodExNepal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        public Order()
        {
            this.OrderDetails = new HashSet<OrderDetail>();
        }
    
        public int OrderId { get; set; }
        public int CustomerId { get; set; }
        public int RestaurantId { get; set; }
        public Nullable<double> Amount { get; set; }
        public Nullable<System.DateTime> DateTime { get; set; }
        public string DeliveryStatus { get; set; }
        public Nullable<bool> IsOrderConfirmed { get; set; }
        public Nullable<int> DeliveryBoyId { get; set; }
        public Nullable<int> VATPercent { get; set; }
        public Nullable<int> RestaurantServiceChargePercent { get; set; }
        public Nullable<int> ServiceChargePercent { get; set; }
        public Nullable<double> DeliveryCharge { get; set; }
        public string FullName { get; set; }
        public string DeliveryAddress { get; set; }
        public string NearestLocation { get; set; }
        public string DeliveryMeOrSelfPickup { get; set; }
        public string HouseNo { get; set; }
        public string SpecialInstruction { get; set; }
        public string Phone { get; set; }
        public string Take_awayDateTime { get; set; }
    
        public virtual Customer Customer { get; set; }
        public virtual DeliveryStaff DeliveryStaff { get; set; }
        public virtual Restaurant Restaurant { get; set; }
        public virtual ICollection<OrderDetail> OrderDetails { get; set; }
    }
}
