//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FoodExNepal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Restaurant
    {
        public Restaurant()
        {
            this.FoodCategories = new HashSet<FoodCategory>();
            this.FoodItems = new HashSet<FoodItem>();
            this.Orders = new HashSet<Order>();
            this.Reviews = new HashSet<Review>();
        }
    
        public int RestaurantId { get; set; }
        public string RestaurantName { get; set; }
        public string RestaurantLogo { get; set; }
        public string Address { get; set; }
        public string PhoneNumber { get; set; }
        public string RestaurantCaption { get; set; }
        public string DetailInfo { get; set; }
        public Nullable<bool> IsServiceChargeApplicable { get; set; }
        public string ServiceChargePercent { get; set; }
        public Nullable<bool> IsVatApplicable { get; set; }
        public string VATPercent { get; set; }
        public string CusineInfo { get; set; }
        public string OpeningTime { get; set; }
        public string MinOrderAmount { get; set; }
        public string PANNumber { get; set; }
        public Nullable<bool> IsFeatured { get; set; }
        public string RestaurantType { get; set; }
        public string Speciality { get; set; }
        public Nullable<int> LocationId { get; set; }
        public string RestaurantImageInDetailPage { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public string Username { get; set; }
        public string Password { get; set; }
        public string Email { get; set; }
        public Nullable<bool> AllowLogin { get; set; }
        public string DeliveryCharge { get; set; }
    
        public virtual ICollection<FoodCategory> FoodCategories { get; set; }
        public virtual ICollection<FoodItem> FoodItems { get; set; }
        public virtual Location Location { get; set; }
        public virtual ICollection<Order> Orders { get; set; }
        public virtual ICollection<Review> Reviews { get; set; }
    }
}
