//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FoodExNepal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class WebsiteProfile
    {
        public int ProfileId { get; set; }
        public string Logo { get; set; }
        public string ContactNumber { get; set; }
        public string HomePageImage { get; set; }
        public string FacebookLink { get; set; }
        public string TwitterLink { get; set; }
        public string WhyFoodExNepalCaption { get; set; }
        public string WhyFoodExNepal { get; set; }
        public string WelcometoFoodexNepal { get; set; }
        public string WelcometoFoodexNepalCaption { get; set; }
        public string GooglePlaystoreLink { get; set; }
        public string ItunesLink { get; set; }
        public string DeliveryCharge { get; set; }
        public string DeliveryChargeOutsideRingRoad { get; set; }
        public string ServiceHour { get; set; }
    }
}
